name: PR Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: pr-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tests:
    name: Build Tests
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Run build tests
        run: |
          set -o pipefail
          make build
