name: PR Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: pr-tests-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-tests:
    name: Build and Coverage
    runs-on: macos-15
    timeout-minutes: 30

    steps:
      - name: Check out source
        uses: actions/checkout@v4

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Lint
        run: make lint

      - name: Run tests with coverage
        run: |
          set -o pipefail
          make coverage

      - name: Install xcresultparser
        run: |
          brew install a7ex/homebrew-formulae/xcresultparser

      - name: Convert xcresult to Cobertura XML
        run: |
          xcresultparser --output-format cobertura \
            build/Coverage.xcresult > build/coverage.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: build/coverage.xml
          fail_ci_if_error: true
          verbose: true
